name: 01_9_Sonar Init Master

on:
  pull_request:
    branches:
      - master

jobs:
  sonar_backend:
    name: ğŸ” Sonar Init Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ğŸ” Scan Backend
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        with:
          projectBaseDir: ./api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}

  sonar_frontend:
    name: ğŸ” Sonar Init Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ğŸ” Scan Frontend
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        with:
          projectBaseDir: ./frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
